# Permalinks
permalink:           pretty

# Setup
title:              Cleo R
tagline:             Test
url:                 http://cleotilderuiz.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Cleo R
  url:               https://twitter.com/
  email:             cleotilderuiz@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cleotilderuiz

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
